spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true