spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/transactions
    username: postgres
    password: postgres
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always